version: '3.4'

services:
  newslettersignup:
    image: newslettersignup
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:3000
